### PR TITLE
enhance: added the webSearchEngine setting again

### LINKED ISSUE #7917: web search engine setting missing
## 💡 Summary

The setting for the web search engine introduced in #3406 is missing.

It seems it was removed in v12 <https://github.com/misskey-dev/misskey/commit/f6154dc0af1a0d65819e87240f4385f9573095cb#diff-1b57999747089126c1d8f750bf413bed9d15fcd81999f00a9cbedff6c745fb52L153-L159>, but the code to select the search engine still is in the client: https://github.com/misskey-dev/misskey/blob/a5bbb6732d8ec03e3e9ae560f0dcc1a31155330c/src/client/components/google.vue#L24-L25

Maybe the setting was just accidentally removed?

## 🙂 Expected Behavior

The user can select a web search engine.

## ☹️ Actual Behavior

Always uses Google. (bad for privacy)

## 📌 Environment

Misskey since v12.0.0

If it is okay to add this again, I would like to do it.

### PR DESCRIPTION
**Pull request by Johann150**
# What
The `webSearchEngine` setting has been added to Client Settings > General. The setting is stored on the device like other client settings.
The default search engine is DuckDuckGo instead of Google. I think it is much better for privacy. If you think it should be another search engine, please let me know and I will change it!

# Why
Fix #7917

# Additional Info
The Japanese Text is from Misskey 11, so I hope it is correct.
https://github.com/misskey-dev/misskey/blob/e6b93c1dbbe5e623dbae679487094d4e34b6248b/locales/ja-JP.yml#L222-L223

### CODE REVIEW

**Comment by syuilo** [comment]
今のところWeb検索機能はMFM上でしか使われてませんが、そのMFMによる検索構文は100%ジョーク機能であって実用性を求めていないため、保守性の観点から、webSearchEngine設定自体を廃止することにします。
Thanks anyway!

**Comment by 4ioskd** [comment]
It seems that webSearchEngine is removed.
But when I click a Search button on MFM, I'm still moved to Google search engine's result page.

google.vue shoule be removed. DuckDuckGo is recommended as a default search engine.
https://github.com/misskey-dev/misskey/blob/f06ded943397ec10b4c0330cb9ba3bbd33ea7121/packages/client/src/components/google.vue

**Comment by ThatOneCalculator** [comment]
> 今のところWeb検索機能はMFM上でしか使われてませんが、そのMFMによる検索構文は100%ジョーク機能であって実用性を求めていないため、保守性の観点から、webSearchEngine設定自体を廃止することにします。 Thanks anyway!

たとえ「ジョーク」であっても、セキュリティ上のリスクはあるのです。 :(

**Comment by ThatOneCalculator** [comment]
> It seems that webSearchEngine is removed. But when I click a Search button on MFM, I'm still moved to Google search engine's result page.
> 
> google.vue shoule be removed. DuckDuckGo is recommended as a default search engine. [`f06ded9`/packages/client/src/components/google.vue](https://github.com/misskey-dev/misskey/blob/f06ded943397ec10b4c0330cb9ba3bbd33ea7121/packages/client/src/components/google.vue)

While Duckduckgo is better than Google, it's still closed-source and ad-based. If we can decide on a Whoogle/SearX instance, that might be better.

**Comment by Johann150** [comment]
This discussion belongs in the currently open issue.

**Pull request closed without merging**
