### PR TITLE
fix(federation): accept HTTP signatures with hs2019

### LINKED ISSUE #3996: cant follow pixelfed users
# Summary

it is impossible to follow pixelfed (or maybe just pixelfed.social?) users

# Expected Behavior

follow user

# Actual Behavior

user not followed and ``deliver failed: 500 Internal Server Error to=https://pixelfed.social/users/user/inbox`` in server log

# Steps to Reproduce
1. open a pixelfed user from your instance
2. click follow
3.

# Environment

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/69224999-cant-follow-pixelfed-users?utm_campaign=plugin&utm_content=tracker%2F51027576&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F51027576&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #8165: Help debugging why Misskey cannot follow an Owncast account
Hello.  In testing ActivityPub Federation support between Owncast and Misskey I found I've been unable to follow an Owncast account from Misskey.  The follow request is handled and accepted by Owncast, but nothing happens on the Misskey side when the `Accept` is sent to it.

Could you point me in the right direction of what might be missing to fix this incompatibility?

## 💡 Summary

Unable to follow an Owncast server from Misskey.  The Follow `Accept` activity from Owncast that is sent from Owncast to Misskey is ignored and the state stays in `Processing...`.

## 🙂 Expected Behavior

`Processing...` should conclude and the user will be seen as Followed.

## ☹️ Actual Behavior

Misskey stays in `Processing...` status and the Owncast user is not successfully followed.

## 📝 Steps to Reproduce

1. Visit an Owncast profile with Misskey.
2. Press "Follow".
3. Owncast receives the Follow request and sends back an `Accept`.
4. Nothing further happens.

An example Owncast profile is: https://misskey.io/@demo@watch.owncast.online

The following `Accept` payload is what is sent to Misskey:

```
{"@context":"https://www.w3.org/ns/activitystreams","actor":"https://OWNCAST_SERVER/federation/user/testing","id":"https://OWNCAST_SERVER/federation/FoC_r6Jng","object":"https://misskey.io/2395e9f0-4e85-42d3-bb27-63180fb5b258","type":"Accept"}
```
Sent to https://misskey.io/users/8vr4n4kqug/inbox

### LINKED ISSUE #8629: Connecting to Diaspora, Lemmy, and Mobilizon instances
## Summary

I'm a new Misskey user and tried to connect to my other Fediverse accounts. Three connections failed: Diaspora (sysad.org), Lemmy (sopuli.xyz), and Mobilizon (events.nixnet.services). Only Friendica has been successful in connecting to everything.

I'd like to be able to see my activity from those other instances/services on Misskey. Is implementing this possible?

My notes on this on Misskey: https://mk.nixnet.social/notes/8zzvj2sm3d

### PR DESCRIPTION
**Pull request by Johann150**
# What
Use a different http-signature module that supports the currently recommended `hs2019` scheme. This is a modified version of the original library that supports `hs2019`, but fixed to interpret `hs2019` as `rsa-sha256` because that is Mastodon's implementation.

# Why
fix #8165
fix #8629
close #3996

### CODE REVIEW

**Comment by mei23** [comment]
The behavior when no algorithm is specified is also changed to rsa-sha256.
So, also fix #6438

**Comment by Johann150** [comment]
When I try to follow an Owncast user with the changes applied I get this error in the task queue:
```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///home/misskey/misskey/packages/backend/node_modules/node-fetch/src/body.js:149:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async signedGet (file:///home/misskey/misskey/packages/backend/built/remote/activitypub/request.js:48:12)
    at async Resolver.resolve (file:///home/misskey/misskey/packages/backend/built/remote/activitypub/resolver.js:46:15)
    at async default (file:///home/misskey/misskey/packages/backend/built/remote/activitypub/kernel/accept/index.js:10:20)
    at async performOneActivity (file:///home/misskey/misskey/packages/backend/built/remote/activitypub/kernel/index.js:57:9)
    at async performActivity (file:///home/misskey/misskey/packages/backend/built/remote/activitypub/kernel/index.js:35:9)
    at async default (file:///home/misskey/misskey/packages/backend/built/remote/activitypub/perform.js:4:5)
    at async Queue.default (file:///home/misskey/misskey/packages/backend/built/queue/processors/inbox.js:126:5)
    at async /home/misskey/misskey/packages/backend/node_modules/bull/lib/p-timeout.js:69:17
```
I think this is already a known issue in Owncast. (https://github.com/owncast/owncast/issues/1690)

**Comment by Johann150** [comment]
See the linked issue, this issue is resolved in the current development version of Owncast and I successfully tested the PR by following `@goodnight@nightly.owncast.tv` 🎉

**Comment by ThatOneCalculator** [comment]
Yep, works great!

**Comment by Johann150** [comment]
Changed to the peertube npm module. Again tested successfully.

**Comment by 4ioskd** [comment]
To test on develop branch and release a next version, i think it's a time to be merged.

**Comment by ThatOneCalculator** [comment]
~~Actually @Johann150 since you switched to the Peertube version, following Owncast accounts doesn't work properly, tried following `@pixel@desu.watch` but it gets stuck on processing :(~~

**Comment by gabek** [comment]
Misskey following Owncast required a workaround (actor objects instead of IRIs) to be added to Owncast that will be released in 0.0.12. 0.0.11 does not have this change.

**Comment by ThatOneCalculator** [comment]
Ah, gotcha. All good then!

**Comment by gabek** [comment]
Feel free to test against https://nightly.owncast.tv/ if you don't have a 0.0.12 instance to test against.

**Comment by ThatOneCalculator** [comment]
<details>
<summary>Yep, nightly works great!</summary>



</details>

**Comment by Johann150** [comment]
> Misskey following Owncast required a workaround (actor objects instead of IRIs)

That issue will be solved with #8689 on our side as well.

**Comment by mei23** [comment]
peertube版は、no algorithmの場合の対応が入ってないから以下はなおらなくなる。
https://github.com/misskey-dev/misskey/pull/8635#issuecomment-1122739888

ただ、別にそんなに重要じゃないのでなくてもいいかも。
(Mastodon pub-relayのバニラくらいしか該当しない)

**Comment by mei23** [comment]
少なくとも結局、これはもう入れて大丈夫と思うのだわ。
今まで`algorithm=hs2019`で飛んできたものを完全に弾いてたのを受け入れるようになるだけだから、害もないはず。

**Comment by syuilo** [comment]
Thanks!

**Pull request merged**
