### PR TITLE
fix: email verify enable logic

### PR DESCRIPTION
**Pull request by Candinya**
## Why

`meta.verifymailAuthKey` -> affects `verifymailApi` -> already handled above
`meta.enableActiveEmailValidation` -> affects whether enable email verify logic -> already handled in if situations

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Comment by Mar0xy** [comment]
I feel like this should be merged for #12564 as this fixes an issue where having validation enabled but no key for verifymail set causing it to not run the else statement to check via the node package instead as it just skips everything else and always defaults to valid.

**Comment by syuilo** [comment]
🙏

**Comment by syuilo** [comment]
lintが失敗してそう

**Comment by Candinya** [comment]
> lintが失敗してそう

should be fixed in #12761

**Pull request merged**
