### PR TITLE
Update from Weblate.

### PR DESCRIPTION
**Pull request by weblate**

### CODE REVIEW

**Comment by nijel** [comment]
I think it would be pity to lose work done on Weblate.

Anyway it would be great if you let us know that you are not using the service to avoid this.

**Comment by syuilo** [comment]
Thank you!
I was unaware that the weblate account was created because I could not receive email from weblate. I locked the repository right now.
I will merge the translations that have been done so far.

**Comment by nijel** [comment]
It was created in May, the ticket system properly sent the mail to you, maybe it has ended up in spam folder :-(.

**Comment by syuilo** [comment]
Merging is complete!

I did upload the files to Crowdin because it does not apply even if I merge the translation files directly into the repository.
So, I close this PR.

Thank you!

**Pull request closed without merging**
