### PR TITLE
feat: add minimize/Fold button for windows

### LINKED ISSUE #10505: Minimize/Fold button for windows
## Summary

occasionally, i open a whole lot of windows of notes for reading later while i scroll the timeline.  
i found myself making those windows very small so they wouldnt take up the whole screen.  
so a minimize button would be quite useful for this scenario.

i made a prototype of this feature, [live on my instance](https://misskey.heonian.org/notes/9d9zk5fw5a). if this seems like a good feature, i could clean up the code and try pull-requesting it.  
try shift-clicking the date, so the note appears in a window, and then try clicking the new minimize button.
here's a video, too:
https://user-images.githubusercontent.com/2979581/230596215-c3dc2eaa-3b09-4a15-8a9c-09a81b5cdbac.mp4

### PR DESCRIPTION
**Pull request by 2minwia**
## What

Adds a minimize / fold button to windows. The button makes windows very small.
image
image

## Why

(copied from the issue)
occasionally, i open a whole lot of windows of notes for reading later while i scroll the timeline.
i found myself making those windows very small so they wouldnt take up the whole screen.
so a minimize button would be quite useful for this scenario.

## Additional info (optional)

Closes #10505

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [x] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Comment by 2minwia** [comment]
(regarding editing en-US.yml (sorry!!!), should i do a force-push to undo the change, or should i just make another commit?)

(also, realized i have a bug in this (you can put a minimized window at the bottom right edge and then unminimize it, and have it go outside the browser). ill wait to commit a patch for this though until i have an answer on the above, just in case i need to force-push (not 100% sure if i can do that after doing another commit, so waiting just to be certain))

**Comment by acid-chicken** [comment]
> (regarding editing en-US.yml (sorry!!!), should i do a force-push to undo the change, or should i just make another commit?)

No problem as long as it is reverted before the merge. So, you don't need a force push.

**Comment by 2minwia** [comment]
> > (regarding editing en-US.yml (sorry!!!), should i do a force-push to undo the change, or should i just make another commit?)
> 
> No problem as long as it is reverted before the merge. So, you don't need a force push.

Got it, thank you! This is fixed (along with the bug-fix) now c:

**Comment by syuilo** [comment]
👍🏻

**Pull request merged**
