### PR TITLE
Disallow renote of direct note

### LINKED ISSUE #11969: ダイレクト投稿をRNできる
(オリジナルは niri-la/misskey.niri.la#56 by @KisaragiEffective)

Originally ダイレクト投稿なRNを削除すると500エラーになる

## 💡 Summary

投稿範囲をダイレクトにしたノートをRNし、そのRNを取り消すとステータスコードが500のレスポンスとエラーが返ってくる

(※おそらく [misskey-dev#10127](https://github.com/misskey-dev/misskey/issues/10127) と同根のバグだと思われるが、upstreamで発生するか検証していないため一旦このリポジトリに記録)

anatawa12追記: そもそもダイレクト投稿がrenoteできるのが誤りでないかとも思っています

## 🥰 Expected Behavior

200などで正常に消去される

## 🤬 Actual Behavior

消去はされているように見えるが、レスポンスでエラーが返ってくる

## 📝 Steps to Reproduce

1. 投稿範囲をダイレクトにしたノートをする
2. そのノートをリノートする
3. リノートを取り消す

### 💻 Frontend
* Model and OS of the device(s):macOS 14.0 23A344 arm64
  
* Browser:firefox 118.0.1 (64 ビット
  
* Server URL: misskey.niri.la
  
* Misskey:2023.9.3-kinel.2

### 🛰 Backend (for server admin)

同上環境の開発環境でも確認しました。

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

### PR DESCRIPTION
**Pull request by anatawa12**
## What

Fixes #11969

ダイレクト投稿をRenoteできるのを修正しました

## Why

多分想定外

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [x] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Comment by anatawa12** [comment]
image

**Comment by anatawa12** [comment]
ready

**Comment by syuilo** [comment]
🙏

**Pull request merged**
