### PR TITLE
fix Dockerfile

### LINKED ISSUE #7762: Docker build failed in 12.90.0
Hello! First of all, I would like to thank all contributors for this unique and fun project! I really like Misskey.

## 💡 Summary

Du to the change of Dockerfile in 12.90.0., `docker build` failed as you can see below.

## 🙂 Expected Behavior

`docker build` should successfully finish.

## ☹️ Actual Behavior

In v12.90.0, it fails as

```:shell
Step 6/18 : RUN git submodule update --init
 ---> Running in 909b730ea6f9
/bin/sh: git: not found
The command '/bin/sh -c git submodule update --init' returned a non-zero code: 127
```

This is actually because `git` is not installed. I've already fixed this. So can I make a PR to develop branch?

## 📝 Steps to Reproduce

1. Just run `docker build -t <your_tag> .`

## 📌 Environment

```
$ docker --version
Docker version 20.10.8, build 3967b7d
```
and GitHub Actions.

### PR DESCRIPTION
**Pull request by junkurihara**
# What

This resolves #7762.

# Why

This PR simply add the installation process of `git` in `docker build`, and allows `.git` directory to be copied before `git submodule`. This PR also makes  Dockerfile a bit neat to reduce the image size by bundling `RUN`s. 

# Additional info (optional)

### CODE REVIEW

**Comment by junkurihara** [comment]
Ah, sorry. The line
```
VOLUME [ "/misskey/.config/" ]
```
should be removed (already removed), which is the change for my own repo.

**Review by syuilo — APPROVED** [review]

**Review by mei23 — APPROVED** [review]
What is Docker?

**Comment by tamaina** [comment]
It might be better to add `misskey-assets/` to .dockerignore, because it will error if it already has done `git submodule update --init`.

**Comment by junkurihara** [comment]
Hey @tamaina,

Thanks for your suggestion. I agree to your idea  from the perspectives of the size of docker image.  Considering the developers who already have files in `misskey-assets`, it should be nicer.

will update shortly.

**Review by tamaina — APPROVED** [review]

**Comment by syuilo** [comment]
Thank you guys🙏

**Comment by tamaina** [comment]
> perspectives of the size of docker image

なんで？と思ってたんだけど、コピーしないからか  
(misskey-assetsを参照する時が来たらコピーしないと問題が起きそう)

**Comment by mei23** [comment]
misskey-assets を除外することを考えるなら、とっとと .config を突っ込むのをなおすべきと思う。
https://github.com/misskey-dev/misskey/pull/7625

**Pull request merged**
