### PR TITLE
fix(ci): publish docker image fails (2)

### PR DESCRIPTION
**Pull request by anatawa12**
## What

https://github.com/misskey-dev/misskey/pull/13325#issuecomment-1947781175

## Additional info (optional)

動作等未確認

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/pull/13325#issuecomment-1947784075

> tags消せば良さそう？

の可能性もありそう

**Comment by zyoshoka** [comment]
https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners には書いてなかったのでもしかするとそうかなと

**Comment by anatawa12** [comment]
ですね。とりあえずこの方針は破棄なのでcloseします。 zyoshokaさんやりますか?

**Comment by zyoshoka** [comment]
やってみます

**Pull request closed without merging**
