### PR TITLE
fix: broken chats

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Continuation of #8951 with the issue I mentioned fixed and @Johann150's overflow suggestion.

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Tested and working on https://stop.voring.me

**Comment by ThatOneCalculator** [comment]
Requesting review from @syuilo

**Comment by ThatOneCalculator** [comment]
@syuilo this seems like a pretty critical fix

**Comment by syuilo** [comment]
🙏🏻

**Pull request merged**
