### PR TITLE
Add me (ThatOneCalculator) as patron

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
# What
Adds me as patron :)

image

### CODE REVIEW

**Comment by Johann150** [comment]
I think the patrons list should be updated in general.

**Comment by acid-chicken** [comment]
> I think the patrons list should be updated in general.

I agree in my opinion, but is the list still treated as a target in our maintenance plan? ref: https://github.com/misskey-dev/misskey/issues/5774#issuecomment-924471695

**Comment by tamaina** [comment]
かつてjoinmisskeyでやっていたように、Misskey Hubで表示するようにしてもいい気がする

定時更新するならjoinmisskeyでやってもいいのか…あんまりやる気がないけど

**Comment by acid-chicken** [comment]
> #### Why Patreon?
> I dedicate most of my free time working on Misskey. By becoming a Patron, you help me to continue developing and nurturing this Open-Source project.
>
> If you donate more than $50 in total, your name will be displayed on the Misskey client!
[&mdash; syuilo is creating Misskey | Patreon](https://github.com/syuilo/misskey)

I got it. This should be automatically maintained in its current state.

**Comment by acid-chicken** [comment]
We managed the list of patrons in README automatically until a few years ago (cbcf3b7599e0a03eb2fc8a33b6f4aad78c80fbeb). According to the documentation for the API we used to do that, we can also [get the total amount paid by patrons](https://docs.patreon.com/#member), so it should be easy to automate this kind of mechanism by rebuilding it using GitHub Actions.

**Comment by acid-chicken** [comment]
Conversely, except for syuilo theirself, we have no way of knowing the total amount paid by patrons without the use of this API.

**Comment by syuilo** [comment]
👍

Some people do not want to be on this list, which makes it difficult to automate.

**Comment by robflop** [comment]
I had been wondering when my name was going to show up there, actually. Did not want to be a bother and do a PR or something because I felt like that'd come off as self-important though. Interesting to know it's just because the pipeline for it was removed.

**Comment by syuilo** [comment]
I regularly export the list of Patreon supporters as a CSV, paste it into a Google spreadsheet, narrow down the list of people who match the criteria to have their names listed, and paste it into the Misskey code. However, it takes a lot of time and effort, and as mentioned above, there are people who support but do not want their names listed, so it might be better to have people who want to be on the list contact us by email or other means.

**Pull request merged**
