### PR TITLE
fix: Unable to generate video thumbnails

### LINKED ISSUE #8693: GenerateVideoThumbnail failed: TypeError: FFmpeg is not a function
## 💡 Summary

Thumbnails for videos I upload or receive are not generated. I get this in the logs:

```
WARN 1   [drive register]        GenerateVideoThumbnail failed: TypeError: FFmpeg is not a function
```

I can manually generate a thumbnail with `ffmpeg` on the server with:

```
ffmpeg -i video.webm -frames:v 1 thumbnail.jpeg
```

## 🥰 Expected Behavior

Thumbnail is generated

## 🤬 Actual Behavior

No thumbnail is generated

## 📝 Steps to Reproduce

1. Upload video
2. No thumbnail

## 📌 Environment

Misskey version: 12.110.1
Your OS: Gentoo Linux
Your browser: Firefox 91.9.0esr

### PR DESCRIPTION
**Pull request by mei23**
# What
Fix #8693

# Why
Fix #8693

# Additional info (optional)
動作確認済み

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Still doesn't seem to work...

image

**Comment by mei23** [comment]
It will not be reflected in past posts.
How about new posts?

**Comment by tamaina** [comment]
I think it is new file, not new post (note).

**Comment by ThatOneCalculator** [comment]
Yea, I deleted my comment since I misunderstood that this is for the drive and not for posts.

**Review by Johann150 — APPROVED** [review]

**Comment by syuilo** [comment]
👍

**Pull request merged**
