### PR TITLE
feat(misskey-js): `POST admin/roles/create`の型を具象化

### LINKED ISSUE #14161: misskey-js: admin/roles/createのpoliciesのスキーマを具現化する
### Summary

`admin/roles/create`の`policies`は`Record<string, never>`ではない

### Purpose

backend/test/e2e/note.tsで実際に使用されていて、基礎ロールに対するオーバーライドとして機能しているため:

https://github.com/misskey-dev/misskey/blob/a5407131d4d15edca924e2718902cefd81e49ee2/packages/backend/test/e2e/note.ts#L471-L477

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

### PR DESCRIPTION
**Pull request by KisaragiEffective**
## What

fix #14161

## Why

issueに記載のため省略

## Additional info (optional)

~~多分CHANGELOGが必要 (後で書く)~~ done

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [x] (If needed) Update CHANGELOG.md
- [x] (If possible) Add tests

### CODE REVIEW

**Comment by KisaragiEffective** [comment]
```
> misskey-js@2024.5.0 api-prod /home/runner/work/misskey/misskey/packages/misskey-js
> pnpm api-extractor run --verbose


api-extractor 7.47.0  - https://api-extractor.com/

Using configuration from ./api-extractor.json
Analysis will use the bundled TypeScript version 5.4.2
*** The target project appears to use TypeScript 5.5.3 which is newer than the bundled compiler engine; consider upgrading API Extractor.
Writing: /home/runner/work/misskey/misskey/packages/misskey-js/temp/misskey-js.api.json
Generating complete API report: /home/runner/work/misskey/misskey/packages/misskey-js/etc/misskey-js.api.md
Warning: You have changed the API signature for this project. Please copy the file "temp/misskey-js.api.md" to "etc/misskey-js.api.md", or perform a local build (which does this automatically). See the Git repo documentation for more info.

API Extractor completed with warnings
/home/runner/work/misskey/misskey/packages/misskey-js:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  misskey-js@2024.5.0 api-prod: `pnpm api-extractor run --verbose`
Exit status 1
Error: Process completed with exit code 1.
```
謎

**Comment by KisaragiEffective** [comment]
single quoteに直したからだった 😓

**Comment by KisaragiEffective** [comment]
ready for review

**Comment by syuilo** [comment]
👍🏻

**Pull request merged**
