### PR TITLE
fix(frontend): Screen Wake Lock APIが正常に動作しない環境でのエラー処理

### PR DESCRIPTION
**Pull request by ragujp**
## What

https://github.com/misskey-dev/misskey/issues/12462

## Why

https://github.com/misskey-dev/misskey/issues/12462

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Comment by tamaina** [comment]
なんとなくpromise-then-catchじゃなくてtry-await-cacth-noneにしたい気がする（雰囲気的な問題）

**Comment by tamaina** [comment]
やっぱナシで（起動時間に影響でそう）

**Comment by syuilo** [comment]
🙏🙏🙏

**Comment by syuilo** [comment]
CHANGELOG要りそう

**Pull request merged**
