### PR TITLE
Person: support movedTo

### PR DESCRIPTION
**Pull request by Mstrodl**
#5475

# What

Supports movedTo attribute on `Person`

# Why

I tried to follow a friend on the wrong account! Now, a warning will appear to tell me they have a different account.

# Additional info (optional)

image

### CODE REVIEW

**Comment by Mstrodl** [comment]
Note: this doesn't touch the renderer at all, and users on misskey can't set it for themselves. This is only for remote users for now.

**Comment by Mstrodl** [comment]
Also, I noticed the wrong locales tag

I don't know japanese, sorry

**Comment by tamaina** [comment]
I have added one commit, please try it.

**Comment by tamaina** [comment]
In this PR, you have not written the Move activity process, so I think movedTo is only written when a new user is acquired. (If actor update is emitted, it's not a problem).

**Comment by tamaina** [comment]
Actor Updateを処理するのはこのPRで実装したい

**Comment by tamaina** [comment]
🙏🙏🙏

**Pull request closed without merging**
