### PR TITLE
enhance: handle URLs in reports

### PR DESCRIPTION
**Pull request by Johann150**
# What
- properly include note URLs in the `object` property of `Flag` activities
- simplify code for rendering `Flag` activities
- remove ability for users to accidentally edit or delete URLs when creating a report
- handle incoming `Flag` activities in a way that the URLs are not displayed as part of the reports content.
- fix small issue in API description for `forwarded` from #8001
# Why
- Admins on other fediverse software can take better actions when it is properly indicated which notes are the report target. (see also https://github.com/misskey-dev/misskey/pull/8001#issuecomment-994833969)
- The display is nicer for moderators and admins when handling reports from other instances or software.

# Additional info
`urls` is an array because incoming reports may include multiple URLs. Also including it as an array in the API adds the ability for clients to have a workflow similar to Mastodon or Pleroma where multiple notes of the same account can be reported at once.

I thought this was harder so I did not immediately include it in #8001, but it turned out to be simpler. Sorry for the additional work.

### CODE REVIEW

**Review by pixeldesu — APPROVED** [review]
Code looks fine and also tested this PR with @Johann150 reporting posts on my instance and vice versa!

**Comment by Johann150** [comment]
NB: Adjusted for the changes that were made since I finished this PR, like for example using ESModules for migrations and fixed some bugs. Updated screenshots below.

<details>
<summary>screenshot of admin UI - outgoing report</summary>

image
</details>

<details>
<summary>screenshot of admin UI - incoming report</summary>

image
</details>

**Comment by ThatOneCalculator** [comment]
Is there a way to get  a little bit of space between the text and the button? Looks a bit squished.

image

**Comment by Johann150** [comment]
image

**Comment by ThatOneCalculator** [comment]
Testing this PR, going to `/admin/abuses` produces a 500 internal server error. 

`

**Comment by Johann150** [comment]
There are many merge conflicts and I do not have time or motivation to refactor to the new code layout.

**Pull request closed without merging**
