### PR TITLE
fix(client): render quote renote CWs as MFM

### LINKED ISSUE #8438: rendering of content warnings is inconsistent
## 💡 Summary

The content warning of a quote renote is not rendered as MFM in `packages/client/src/components/note-simple.vue`:
https://github.com/misskey-dev/misskey/blob/08bace6c7db7b34f271c270c0f81d70f0b412438/packages/client/src/components/note-simple.vue#L8

But content warnings are rendered as MFM for other notes:
https://github.com/misskey-dev/misskey/blob/08bace6c7db7b34f271c270c0f81d70f0b412438/packages/client/src/components/note.vue#L46

## 🥰 Expected Behavior

The content warning is always rendered as MFM.

## 🤬 Actual Behavior

The content warning is displayed as plain text.

## 📝 Steps to Reproduce

1. Create a note that contains MFM in the content warning.
2. Quote that note.
3. The content warning of the quoted note displays as plain text.

## 📌 Environment

Misskey version: 12.108.1

### PR DESCRIPTION
**Pull request by pixeldesu**
# What

Renders CWs of simple note displays with MFM

# Why

Fixes #8438

### CODE REVIEW

**Comment by Johann150** [comment]
<details>
<summary>screenshot before</summary>

image
</details>

<details>
<summary>screenshot after</summary>

image
</details>

**Review by Johann150 — APPROVED** [review]

**Comment by syuilo** [comment]
🙏

**Pull request merged**
