### PR TITLE
enhance: Styled Repair Tools (BIOS, CLI, Flush)

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
# What
Adds style for BIOS (now Repair Tool), CLI (now Simple Client), and Flush.

# Why
Compliments #8946

# Additional info (optional)

Live on:

- https://stop.voring.me/cli
- https://stop.voring.me/bios
- https://stop.voring.me/flush

Screenshots:

image
image
(Note that the fail is on purpose, I ran it in an incognito window so my actual preferences wouldn't get flushed)
image

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Flush is broken

**Comment by ThatOneCalculator** [comment]
Requesting review from @syuilo , apologies for the lots of pings ^^;

**Comment by futchitwo** [comment]
In my opinion🍠, posts and local storage are easier to read in the traditional left-aligned style rather than centered.

**Comment by aprilthepink** [comment]
I love how this PR literally is just letting hang here.

**Comment by tamaina** [comment]
I can't merge because of `fatal: refusing to merge unrelated histories`

**Pull request closed without merging**
