### PR TITLE
fix: nodeinfoにenableMcaptchaとenableTurnstileが無い

### LINKED ISSUE #13385: nodeinfo(2.1)にはenableMcaptchaとenableTurnstileが無い
### 💡 Summary

例えば https://misskey.niri.la/nodeinfo/2.1 では、enableHcaptchaとenableRecaptchaはありますが、enableMcaptchaとenableTurnstileはありません。(にりらみすきー部では現在Turnstileが有効です)

Related: https://github.com/misskey-dev/misskey/issues/13320 (このまま実装が行われると誤判定が発生することになります)

### 🥰 Expected Behavior

全部ある

### 🤬 Actual Behavior

一部ない

### 📝 Steps to Reproduce

nodeinfoを見る

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): any
* Browser: any
* Server URL: https://misskey.niri.la/ , https://misskey.io/ など
* Misskey: 2024.2.0-kinel.1 , 2024.2.0-io.2b など
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

### PR DESCRIPTION
**Pull request by anatawa12**
## What

Fix #13385

## Why

See issue

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [x] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Comment by anatawa12** [comment]
```
The API report is up to date: temp/misskey-js.api.md
```
と言われますね

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/actions/runs/7949635936/job/21701023863?pr=13387 なんかおちかたがへん

**Comment by anatawa12** [comment]
rerunしたら治った

**Comment by syuilo** [comment]
🙏🏻

**Pull request merged**
