### PR TITLE
feat: Undo Accept

### PR DESCRIPTION
**Pull request by nullobsi**
# What

Add a "Break Follow" feature.
image

It will remove the other person from following you.

# Why

For people with follower-approval accounts, they may want to remove a person from access. Blocking and then unblocking can be annoying, or send the wrong message. Therefore, "breaking follow" is a good solution.

# Additional info (optional)

- [ ] needs tests

### CODE REVIEW

**Comment by Johann150** [comment]
There has been some discussion on whether to introduce something like this in #7899, although for all users, not only those with manual approved follows.

**Comment by nullobsi** [comment]
This works for accounts with and without approve followers on

**Comment by nullobsi** [comment]
Ah, it seems this is already a thing but under "Reject Follow" for Mastodon. So I'll update the AP implementaton to use that for better compatibility

**Comment by syuilo** [comment]
🆒

**Pull request merged**
