### PR TITLE
packages(backend): update package.json

### PR DESCRIPTION
**Pull request by Yonle**
## What
See the diff for package.json file.

Instead of `^`, Use `>=`

## Why

```
ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your Node version is incompatible with "/home/misskey/misskey/packages/backend".

Expected version: ^20.10.0
Got: v21.6.1

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
```

Replacing `^` as `>=` in the beginning of `engines.node` field will solve this issue.

## Checklist
- [ X Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [X] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Comment by acid-chicken** [comment]
Currently we don't target Node.js 21.x for support. Therefore, the current specifier is working as intended.

**Comment by Yonle** [comment]
> Currently we don't target Node.js 21.x for support. Therefore, the current specifier is working as intended.

But it blocks package manager to continue on newer nodejs that is installed in the system.

**Comment by acid-chicken** [comment]
> > Currently we don't target Node.js 21.x for support. Therefore, the current specifier is working as intended.
> 
> But it blocks package manager to continue on newer nodejs that is installed in the system.

I think this is behaving as it should, are you having trouble with anything?

**Comment by Yonle** [comment]
> > > Currently we don't target Node.js 21.x for support. Therefore, the current specifier is working as intended.
> > 
> > But it blocks package manager to continue on newer nodejs that is installed in the system.
> 
> I think this is behaving as it should, are you having trouble with anything?

As i pasted before, When i am doing any operation with `pnpm` command including starting the server itself, It gives me this error & simply does not let me continue:

```
ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your Node version is incompatible with "/home/misskey/misskey/packages/backend".

Expected version: ^20.10.0
Got: v21.6.1

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
```

I am not using `nvm`, But i have nodejs v21 installed in my system.

**Comment by KisaragiEffective** [comment]
Generally you shouldn't use unsupported version, use nvm or likewise tool to use supported version if that's from system-wide package manager.
(Disclaimer: I am not a maintainer)

**Comment by acid-chicken** [comment]
Compatibility between versions of Node.js is [probably more unstable than everyone thinks](https://github.com/misskey-dev/misskey/issues/10778#issuecomment-1537113000). This instability can be caused by ABI, bugs in the runtime implementation, or by feature additions that are not bugs. Moreover, the version you are using straddles the major version. So what semantic versioning is saying is that there are breaking changes. Actually it might work when you override the specifier in your environment, but it is not currently in our plans to confirm and/or recommend them.

**Comment by anatawa12** [comment]
We are not planned to support node v21 so closing this PR.

**Pull request closed without merging**
