### PR TITLE
fix(frontend): Fix cat ears are awkward on reply modal

### LINKED ISSUE #11279: Cat ears seems awkward on reply modal.
## 💡 Summary

On reply modal, the cat ear seems quite awkward. Tried on Firefox 115.0.2 & Chrome 114.0. 5735. 199 and both seems wrong. I've tried to search this issue with 'cat', 'ear' to prevent making duplicated issue, but I'm really sorry if this issue is duplicated. 

## 🥰 Expected Behavior

제목 없음

I think cat ears should be seen fully on reply modal.

or

fixed
giving a tag a margin-top:10px might fix this problem, but for only cat eared profiles.

## 🤬 Actual Behavior

image

## 📝 Steps to Reproduce

1. Write a note. 
2. Get a reply from anyone who have a cat ear.
3. Try to reply.

### 💻 Frontend
* Model and OS of the device(s): Windows 10 Education 22H2
* Browser: Firefox 115.0.2 & Chrome 114.0.5735.199
* Server URL: sns.lemondouble.com
  
* Misskey: 13.14.0-beta.2

### PR DESCRIPTION
**Pull request by RieLCho**
## What

This will fix #11279, shows cat ears on reply modal.

but this is the very easiest (might be naive) way to fix this issue. If hurting css is not enough for misskey maintainers, i will try to find another way.

## Why

misskey's cat ears are so cute. cute enough not to hidden by modal header.

## Additional info (optional)

스크린샷 2023-07-18 오후 3 03 43

스크린샷 2023-07-18 오후 3 04 06

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Review by saschanaz — APPROVED** [review]

**Comment by tamaina** [comment]
🙏

**Comment by acid-chicken** [comment]
これ非リプライ投稿画面でスタイル崩れ起こしてない？

**Comment by RieLCho** [comment]
見つけったらおしえてください🥲

**Comment by RieLCho** [comment]
image

image

やっば

**Pull request merged**
