### PR TITLE
Add missing migrations

### LINKED ISSUE #7210: ERROR:  value too long for type character varying(1024)
## 💡 Summary

Getting 100+ errors for this:

`ERROR:  value too long for type character varying(1024)`
`STATEMENT:  UPDATE "user_profile" SET "url" = $2, "fields" = $3, "description" = $4, "birthday" = $5, "location" = $6 WHERE "userId" = $1`

## 📌 Environment

Misskey 12.69.0 PostgreSQL 10.15

### LINKED ISSUE #7369: QueryFailedError: Insert Into - value too long
## 💡 Summary

This is `INSERT INTO` error which is different from past `UPDATE` bug report

`INFO 1#011[remote ap]#011Creating the Person: https://loma.ml/profile/hubble`
`
## 🙂 Expected Behavior

No error in postgresql log

## ☹️ Actual Behavior
```

INFO 1#011[remote ap]#011Creating the Person: https://loma.ml/profile/hubble
ERR  1#011[remote ap]#011QueryFailedError: value too long for type character varying(1024)

ERROR:  value too long for type character varying(1024)
STATEMENT:  INSERT INTO "user_profile"("userId", "location", "birthday", "description", "fields", 
"lang", "url", "email", "emailVerifyCode", "emailVerified", "emailNotificationTypes", "twoFactorTempSecret", 
"twoFactorSecret", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "password", 
"clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote",

"receiveAnnouncementEmail", "pinnedPageId", "integrations", "enableWordMute", "mutedWords", 
"mutingNotificationTypes", "userHost") VALUES ($1, $2, $3, $4, $5, DEFAULT, $6, DEFAULT, DEFAULT, 
DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, 
DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, 
DEFAULT, $7) RETURNING "fields", "emailVerified", "emailNotificationTypes", "twoFactorEnabled", 
"securityKeysAvailable", "usePasswordLessLogin", "clientData", "room", "autoAcceptFollowed", "noCrawle", 
"alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "integrations", 
"enableWordMute", "mutedWords", "mutingNotificationTypes"


```

## 📝 Steps to Reproduce

1. Not sure how to reproduce
2. This was found in the postgresql log

## 📌 Environment

Misskey 12.74.1  PostgreSQL 10.15

### LINKED ISSUE #7548: failed to resolve remote user: QueryFailedError: value too long for type character varying(1024)
## 💡 Summary

Trying to follow a remote user by going to https://misskey.kusoneko.moe/@murabito@lets.bemoe.online
The page returns an error instead of loading the user's profile
I went to https://catgirl.life/@murabito@lets.bemoe.online and it loads properly. I'm unsure if they've updated to 12.82.0 yet or not however.

## 🙂 Expected Behavior

Load the remote user's profile.

## ☹️ Actual Behavior

"An error occured." page with the Retry button and the following logs:

```
1m ago [remote.resolve-user] WebFinger for murabito@lets.bemoe.online
1m ago [remote.resolve-user] return new remote user: murabito@lets.bemoe.online
1m ago [remote.ap] Creating the Person: https://lets.bemoe.online/users/murabito
1m ago [api] failed to resolve remote user: QueryFailedError: value too long for type character varying(1024)
1m ago [remote.ap] QueryFailedError: value too long for type character varying(1024)
```

When running `journalctl -u misskey`, at the end, the following error messages show:

```
May 31 17:45:28 kusoneko.moe misskey[2331401]: Error: invalid person: invalid name
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at validatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:56:20)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at Object.updatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:254:17)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at runMicrotasks (<anonymous>)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 31 17:45:28 kusoneko.moe misskey[2331401]: Error: invalid person: invalid name
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at validatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:56:20)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at Object.updatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:254:17)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at runMicrotasks (<anonymous>)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 31 17:45:28 kusoneko.moe misskey[2331401]: Error: invalid person: invalid name
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at validatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:56:20)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at Object.updatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:254:17)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at runMicrotasks (<anonymous>)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 31 17:45:28 kusoneko.moe misskey[2331401]: Error: invalid person: invalid name
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at validatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:56:20)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at Object.updatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:254:17)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at runMicrotasks (<anonymous>)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 31 17:45:29 kusoneko.moe misskey[2331401]: Error: invalid person: invalid name
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at validatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:56:20)
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at Object.updatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:254:17)
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at runMicrotasks (<anonymous>)
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 31 17:45:29 kusoneko.moe misskey[2331401]: Error: invalid person: invalid name
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at validatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:56:20)
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at Object.updatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:254:17)
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at runMicrotasks (<anonymous>)
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Which is a weird error message since the user does exist and is loadable on another misskey instance.

## 📝 Steps to Reproduce

1. Go to https://yourmisskeyinstance.tld/@murabito@lets.bemoe.online
2. Receive error page

## 📌 Environment

Misskey v12.82.0
Ubuntu v20.04
Node v14.15.4
PostgreSQL v13
Elasticsearch v7.13.0
Redis v6.2.3

### PR DESCRIPTION
**Pull request by mei23**
## Summary
作成されてないマイグレーションスクリプトを作成

Fix #7548
Fix #7210
Fix #7369
Related #4809

### CODE REVIEW

**Review by wiredsis — APPROVED** [review]
Seems to indeed mitigate the issue.

**Comment by syuilo** [comment]
🙏🙏🙏

**Comment by Kusoneko** [comment]
> ## Summary
> 
> 作成されてないマイグレーションスクリプトを作成
> 
> Fix #7548
> Fix #7210
> Fix #7369
> Related #4809

Thank you for this fix, I can't wait for it to be deployed on the master branch. I would like to mention that I also had the following PostgreSQL errors related to these issues that I mentioned somewhere in my issue (#7548) which, as I can see from the changes here, wouldn't be fixed by this as the migrations don't affect the table that is affected by the issue:

```
2021-05-31 18:03:58.607 UTC [2431464] misskey@misskey ERROR:  value too long for type character varying(512)
2021-05-31 18:03:58.607 UTC [2431464] misskey@misskey STATEMENT:  INSERT INTO "drive_file"("id", "createdAt", "userId", "userHost", "md5", "name", "type", "size", "comment", "blurhash", "properties", "storedInternal", "url", "thumbnailUrl", "webpublicUrl", "accessKey", "thumbnailAccessKey", "webpublicAccessKey", "uri", "src", "folderId", "isSensitive", "isLink") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, DEFAULT, DEFAULT, $14, $15, $16, $17, $18, $19, $20, $21) RETURNING "properties", "isSensitive", "isLink"
2021-05-31 18:11:05.309 UTC [2438645] misskey@misskey ERROR:  value too long for type character varying(512)
2021-05-31 18:11:05.309 UTC [2438645] misskey@misskey STATEMENT:  INSERT INTO "drive_file"("id", "createdAt", "userId", "userHost", "md5", "name", "type", "size", "comment", "blurhash", "properties", "storedInternal", "url", "thumbnailUrl", "webpublicUrl", "accessKey", "thumbnailAccessKey", "webpublicAccessKey", "uri", "src", "folderId", "isSensitive", "isLink") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, DEFAULT, DEFAULT, $14, $15, $16, $17, $18, $19, $20, $21) RETURNING "properties", "isSensitive", "isLink"
```

After looking into the `drive_file` table column descriptions, the following columns are of the type `character varying(512)`:

- comment
- url
- thumbnailUrl
- webpublicUrl
- uri
- src

I am however unsure which of these columns are the issue.

Thank you,
Kusoneko

**Comment by mei23** [comment]
I think it's probably an external URL

Not federated (yet). 
- comment

Generated by Misskey. So it won't exceed. 
- url
- soonoonUrl
- webpublicUrl 

Based on an external source. It may exceed.
- uri
- src

**Pull request merged**
