### PR TITLE
Migrate to Vue3

### LINKED ISSUE #2945: モバイルの設定画面をページで分割してほしい
# Summary
#2944 と同じような理由で、1つの長いビューの中にカードで分割された設定をページで分割してほしい。

# Environment
mobile

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64992367-?utm_campaign=plugin&utm_content=tracker%2F51027576&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F51027576&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #5831: TypeError widgetsEditButton is undefined
## 💡 Summary

Misskey v12.0.0-alpha.14
TypeError: this.$refs.widgetsEditButton is undefined

## 📌 Environment

nginx 1.14.0 - postgres 10.10 - node 12.14.1 - npm 6.13.4 - yarn 1.21.1

### LINKED ISSUE #5834: 各ページのコンポーネントの読み込み状態のハンドリング
## Summary

読み込み中とか読み込み失敗とかをわかるようにする
https://jp.vuejs.org/v2/guide/components-dynamic-async.html#%E3%83%AD%E3%83%BC%E3%83%89%E7%8A%B6%E6%85%8B%E3%81%AE%E3%83%8F%E3%83%B3%E3%83%89%E3%83%AA%E3%83%B3%E3%82%B0

### LINKED ISSUE #6090: Upload from URL does not work
## 💡 Summary

When writing a new note, trying to upload a file from a URL outputs an error message in the browser developer console. 

## 🙂 Expected Behavior

A form to enter an URL from which to upload the file should appear.

## ☹️ Actual Behavior

Nothing happens, error in browser developer console.

## 📝 Steps to Reproduce

1. Try to write a new note
2. Click on Upload file and then upload from url
3. Look at developer console and see error

vivaldi_2020-02-25_20-24-15

## 📌 Environment

- Likely all browsers, tested: Vivaldi 2.11.1811.41 (Chromium based) and Firefox 73.0.1
- Misskey v12.21.0 (Misskey.io)

### LINKED ISSUE #6133: [v12] アップロードされたファイルが管理できない
## 📝 Steps to Reproduce

1.
2.
3.

### LINKED ISSUE #6387: PCでタイムラインを簡単に切り替えられるようにする
## Summary
簡単に言うと・・・
LSRYZENCapture1082
▲これを復活させる

## ｋｗｓｋ
 - 現状のUIはスマートフォン等のタッチデバイスに最適化されすぎていてPCでは使いにくい箇所がある
- v11ユーザーからの意見で特に必要だと感じた
>v11ではTLの切り替えがワンクリックでできるが、v12は選択式なのでクリック数が増えてる
>https://misskey.dev/@c0_ke/pages/1589472585817

- さすがにv11そのままのUIは適さない恐れがあるため、Syuilo Design Systemに沿ったv12版を作るべきだと思う

### LINKED ISSUE #6392: UI Suggestion: ホームをタブ式に
## Summary
image

こんな感じで

### LINKED ISSUE #6425: UIの上部のマージンは必要？
## Summary
image

image

画像のようにページの上部にマージンがつくけど、私的にはいらないとおもう

### LINKED ISSUE #6560: ウィンドウ復活
## Summary

チャットなどの画面をアプリ内ウィンドウで開けるようにする
ポップアウトもまた実装したい

### LINKED ISSUE #6569: ValidationError: The blurhash string must be at least 6 characters
## 💡 Summary

ValidationError: The blurhash string must be at least 6 characters @syuilo 

## 🙂 Expected Behavior

No validation error

## ☹️ Actual Behavior

```
ValidationError: The blurhash string must be at least 6 characters
    e https://misskey/assets/app.12.42.0.js:2
    o https://misskey/assets/app.12.42.0.js:2
    default https://misskey/assets/app.12.42.0.js:2
    draw https://misskey/assets/app.12.42.0.js:2
    mounted https://misskey/assets/app.12.42.0.js:2
    Vt https://misskey/assets/app.12.42.0.js:2
```

## 📝 Steps to Reproduce

1. Update to v12.42.0
2. Visit homepage
3. Error

## 📌 Environment
v12.42.0

### LINKED ISSUE #6579: ノートの添付画像の表示をcoverではなくcontainにしたい
## Summary

画像の全てを確認するのに都度クリックしてフルサイズの画像を読み込まないといけなくて不便
でもcontainだとblurhashと併用することが難しいのでアイデア募集中

### LINKED ISSUE #6666: ダッシュボードから他のページに遷移すると左右のウィジェットカラムが非表示のまま
## 💡 Summary

ダッシュボードに適用されているFull Viewモードが、他のページに遷移されても解除されない模様

## 🙂 Expected Behavior

ダッシュボードから他のページに遷移したらFull Viewが解除される

## ☹️ Actual Behavior

解除されない

## 📝 Steps to Reproduce

1. https://${host}/instance を開く
2. 他のページに戻る

## 📌 Environment

Misskey 12.47.0

### PR DESCRIPTION
**Pull request by syuilo**
## Summary
Vue2をVue3に移行。
それに合わせて内部の大幅なリファクタリングも行っています。

将来的には全てのコンポーネントをComposition APIを利用したものに移行したいが、このPRでは基本的にやらない

## Tasks
- [x] filters - https://v3.vuejs.org/guide/migration/filters.html#overview
- [x] directives - https://v3.vuejs.org/guide/migration/custom-directives.html#overview
- [x] async component - https://v3.vuejs.org/guide/migration/async-components.html
- [x] functional component
- [x] render function api - https://v3.vuejs.org/guide/migration/render-function-api.html
- [x] watch - no longer supports dot-delimited string paths, use a computed function as the parameter instead
- [x] Migrate v-model - https://v3.vuejs.org/guide/migration/v-model.html#migration-strategy
- [x] Some transition classes got a rename - https://v3.vuejs.org/guide/migration/transition.html#overview
- [x] `beforeDestroy` `destroyed` --> `beforeUnmount` `unmounted`
- [x] Defining Custom Events - https://v3.vuejs.org/guide/component-custom-events.html#defining-custom-events
  - [x] click
  - [x] mouseover
  - [x] etc
- [x] events $on $once $off
- [x] remove Vue.set
- [ ] ref with v-for - https://v3.vuejs.org/guide/migration/array-refs.html, https://github.com/vuejs/vue-next/issues/1166, https://composition-api.vuejs.org/api.html#template-refs
- [x] Attributes coercion strategy changed - https://v3.vuejs.org/guide/migration/attribute-coercion.html#overview
  - data- 系
- [x] Watch on Arrays - https://v3.vuejs.org/guide/migration/watch.html
- [ ] 0023-scoped-styles-changes - https://github.com/vuejs/rfcs/blob/master/active-rfcs/0023-scoped-styles-changes.md
  - [x] ::v-deep usage as a combinator has been deprecated. Use ::v-deep(<inner-selector>) instead.
  - [ ] Targeting / Avoiding Slot Content
- [x] ダイアログリファクタ
  - [x] root.dialog
  - [x] post form window
  - [x] window
  - [x] menu
  - [x] tooltip
  - [x] emoji picker
  - [x] reaction picker
  - [x] visibility picker
  - [x] drive file select
  - [x] notification setting window
  - [x] url preview
  - [x] signin
  - [x] signup
  - [x] form-window
  - [x] toast
- [x] remove destroyDom
- [x] user-preview.ts
- [ ] v-autocomplete
- [x] selectDriveFile
- [x] selectDriveFolder
- [x] mk-radio fix
- [x] search.ts
- [ ] updateBanenr
- [ ] updateAvatar
- [x] keyboard shortcuts
- [x] バグ潰し
- [ ] https://github.com/vuejs/vue-next/issues/2349

### vue-router
- [x] New `history` option to replace `mode` - https://next.router.vuejs.org/guide/migration/#new-history-option-to-replace-mode
- [x] Removed `*` (star or catch all) routes - https://next.router.vuejs.org/guide/migration/#removed-star-or-catch-all-routes
- [x] All navigations are now always asynchronous - https://next.router.vuejs.org/guide/migration/#all-navigations-are-now-always-asynchronous
- [x] `scrollBehavior` changes - https://next.router.vuejs.org/guide/migration/#scrollbehavior-changes

## Thirdparty library status
- [x] vue-i18n
- [x] vue-fontawesome
  - [ ] Vue 3 props aren't reactive - https://github.com/FortAwesome/vue-fontawesome/issues/250
- [x] vuedraggable - https://github.com/SortableJS/Vue.Draggable/issues/881
  - ✔️  altnative - https://github.com/anish2690/vue-draggable-next
- [x] ~~portal-vue - https://github.com/LinusBorg/portal-vue/issues/300~~
- [ ] vue-prism-editor - https://github.com/koca/vue-prism-editor/issues/90
- [x] ~~v-animate-css - https://github.com/jofftiquez/v-animate-css~~
- [ ] vue-json-pretty - https://github.com/leezng/vue-json-pretty
- [ ] vue-prism-component - https://github.com/egoist/vue-prism-component/issues/26

---

Resolve #2945
Resolve #5834
Resolve #6387
Resolve #6392
Resolve #6133
Resolve #6090
Resolve #6579
Resolve #6560
Close #6666
Close #5831
Close #6425
Fix #6569

### CODE REVIEW

**Comment by YuzuRyo61** [comment]
頑張れ❤頑張れ❤

**Comment by SanMurakami** [comment]
無理しない程度に無理して

**Comment by EbiseLutica** [comment]
むぎゅっ

**Comment by atsukotominaga** [comment]
がんばえ〜💪

**Pull request merged**
