### PR TITLE
Add double underscore syntax for bold markdown

### PR DESCRIPTION
**Pull request by ibrokemypie**
# Summary
see https://github.com/syuilo/misskey/pull/3732
this allows bold text through either `**text**` or `__text__`

### CODE REVIEW

**Review by AyaMorisawa — APPROVED** [review]

**Review by acid-chicken — CHANGES_REQUESTED** [review]
Some of invalid syntaxes (e.g. `**bold__`) are allowed by this regex.

**Comment by ibrokemypie** [comment]
@acid-chicken that has now been solved, thanks!

**Comment by AyaMorisawa** [comment]
* [x] some test cases in ./test/mfm.ts should be changed or added

**Comment by ibrokemypie** [comment]
@AyaMorisawa have addressed, I think, though I cant run tests for some reason

**Review by acid-chicken — CHANGES_REQUESTED** [review]
The tests were failed on my computer.

```diff
      + expected - actual

         {
           "children": []
           "node": {
             "props": {
      -        "text": "**foo__"
      +        "text": "foo"
             }
             "type": "text"
           }
         }

      at Context.it (test/mfm.ts:192:12)
```

**Comment by ibrokemypie** [comment]
ah, sorry, wasnt able to run the tests but have worked it out and fixed it now

**Review by acid-chicken — APPROVED** [review]
great work :shipit:

**Review by AyaMorisawa — APPROVED** [review]

**Comment by syuilo** [comment]
Thank you!
As in #3916, I would like to enable this syntax only with the alphabet.

**Pull request merged**
