### PR TITLE
Supports Unicode Emoji 14.0

### LINKED ISSUE #8505: Supports Unicode Emoji 14.0
## Summary

Unicode Emoji 14.0 に対応したいが、Assetsが [@discordapp/twemoji](https://github.com/discord/twemoji) に依存しているのでこれが更新されないと対応できない。
やはり misskey-dev にforkしてnpm publishするしかない？
経緯: https://github.com/misskey-dev/misskey/pull/7897

## Motivation

これが出来れば (絵文字対応に関しては) Discord側の更新を待たずに出来るようになる

### PR DESCRIPTION
**Pull request by mei23**
# What
Supports Unicode Emoji 14.0
Update mfm-js to [0.22.0](https://github.com/misskey-dev/mfm.js/blob/develop/CHANGELOG.md#0220)

- [x] `mfm.js`の`twemoji-parser`のバージョンを上げてpublishして参照する必要がある

# Why
Resolve #8505

# Additional info (optional)
🫠 🫢 🫣 🫡 🫥 🫤 🥹 🫱 🫲 🫳 🫴 🫰 🫵 🫶 🫦 🫅 🫃 🫄 🧌 🪸 🪷 🪹 🪺 🫘 🫗 🫙 🛝 🛞 🛟 🪬 🪩 🪫 🩼 🩻 🫧 🪪 🟰
image

### CODE REVIEW

**Comment by Johann150** [comment]
If merged, close #8542 & https://github.com/misskey-dev/assets/pull/2

**Comment by mei23** [comment]
🎉
image

**Review by syuilo — APPROVED** [review]

**Comment by ThatOneCalculator** [comment]
Works great!! https://stop.voring.me/notes/90lomueluw

**Comment by ThatOneCalculator** [comment]
I feel like this should be merged before the 12.111.x release.

**Comment by syuilo** [comment]
👍

**Pull request merged**
